# Build stage
FROM node:24-alpine AS build

WORKDIR /app

COPY package*.json yarn.lock ./
RUN yarn install

COPY . .

RUN yarn build


# Production stage
FROM node:24-alpine

WORKDIR /app

RUN adduser -D -u 65532 appuser && chown -R appuser:appuser /app

RUN yarn global add serve

USER appuser

COPY --from=build /app/build ./build

EXPOSE 3000

CMD [ "serve", "-s", "build", "-l", "3000" ]
